[tool.black]
line-length = 100
target-version = ['py38']
force-exclude = '''
/(
    mlflow/protos/
  | mlflow/ml_package_versions\.py$
  | tests/protos/
  | examples/recipes/
)
'''

[tool.ruff]
line-length = 100
target-version = "py38"
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"
select = [
  "E",
  "F",
  "C4",
  "I",
  "PLR0402",
  "PT001",
  "PT002",
  "PT003",
  "PT006",
  "PT007",
  "PT009",
  "PT010",
  "PT011",
  "PT012",
  "PT013",
  "PT014",
  "PT018",
  "PT022",
  "PT023",
  "PT026",
  "PT027",
  "RUF010",
  "UP004",
  "UP008",
  "UP011",
  "UP012",
  "UP015",
  "UP030",
  "UP031",
  "UP032",
  "UP034",
  "SIM101",
  "T20",
  "TID252",
]
force-exclude = true
ignore = [
  "E721",  # type-comparison
  "E402",  # module-import-not-at-top-of-file
  "E501",  # line-too-long
  "E741",  # ambiguous-variable-name
  "F403",  # undefined-local-with-import-star
  "F811",  # redefined-while-unused
]
extend-exclude = [
  "setup.py",
  "docs",
  "examples",
  "mlflow/protos",
  "mlflow/ml_package_versions.py",
  "mlflow/server/js",
  "mlflow/store/db_migrations",
  "mlflow/temporary_db_migrations_for_pre_1_users",
  "tests/protos",
]

[tool.ruff.per-file-ignores]
"dev/*" = ["T201", "PT018"]
"mlflow/*" = ["PT018"]

[tool.ruff.flake8-pytest-style]
mark-parentheses = false
fixture-parentheses = false
raises-require-match-for = ["*"]

[tool.ruff.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.isort]
forced-separate = ["tests"]
